### ISSUE TITLE
github workflow needs to retrieve submodules

### ISSUE THREAD

**Issue by edsiper** [fluent/ctraces#1]
In the recent changes, now we need to retrieve the submodules, but this is not expressed in the workflows file so CI is failing

cc: @patrick-stephens

**Comment by patrick-stephens** [comment]
Sure, I'll have a look - I think all we need is to add `submodules: true` to these steps: https://github.com/actions/checkout

```yaml
- uses: actions/checkout@v3
  with:
    submodules: true
```
